TigerSounds:
  Version: 1.8 & 1.9 spigot
  Creator: MrTigreroux
  Description: Plugin de recensement des sons Minecraft.
  Finished on: 15/06/2016
Config:
  PermissionRequired: yes
  ShowSoundsList: yes
  DefaultSoundIcon: Material-Note_block
  DefaultGroupIcon: Skull-MHF_Chest
  ColorCharacter: '&'
  LineBreakSymbol: "//"
  MenuSound: ENTITY_ITEM_PICKUP
  ErrorSound: ENTITY_ITEM_BREAK